/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AskDanteRouteImport } from './routes/ask-dante'
import { Route as CantosRouteImport } from './routes/cantos'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as EmpyreanRouteImport } from './routes/empyrean'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ParadisoRouteImport } from './routes/paradiso'
import { Route as PurgatorioRouteImport } from './routes/purgatorio'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as SearchRouteImport } from './routes/search'
import { Route as InfernoIndexRouteImport } from './routes/inferno.index'
import { Route as InfernoSlugRouteImport } from './routes/inferno.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AskDanteRoute = AskDanteRouteImport.update({
  id: '/ask-dante',
  path: '/ask-dante',
  getParentRoute: () => rootRouteImport,
} as any)
const CantosRoute = CantosRouteImport.update({
  id: '/cantos',
  path: '/cantos',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpyreanRoute = EmpyreanRouteImport.update({
  id: '/empyrean',
  path: '/empyrean',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ParadisoRoute = ParadisoRouteImport.update({
  id: '/paradiso',
  path: '/paradiso',
  getParentRoute: () => rootRouteImport,
} as any)
const PurgatorioRoute = PurgatorioRouteImport.update({
  id: '/purgatorio',
  path: '/purgatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const InfernoIndexRoute = InfernoIndexRouteImport.update({
  id: '/inferno/',
  path: '/inferno/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfernoSlugRoute = InfernoSlugRouteImport.update({
  id: '/inferno/$slug',
  path: '/inferno/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask-dante': typeof AskDanteRoute
  '/cantos': typeof CantosRoute
  '/characters': typeof CharactersRoute
  '/empyrean': typeof EmpyreanRoute
  '/journey': typeof JourneyRoute
  '/paradiso': typeof ParadisoRoute
  '/purgatorio': typeof PurgatorioRoute
  '/quiz': typeof QuizRoute
  '/search': typeof SearchRoute
  '/inferno/$slug': typeof InfernoSlugRoute
  '/inferno/': typeof InfernoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask-dante': typeof AskDanteRoute
  '/cantos': typeof CantosRoute
  '/characters': typeof CharactersRoute
  '/empyrean': typeof EmpyreanRoute
  '/journey': typeof JourneyRoute
  '/paradiso': typeof ParadisoRoute
  '/purgatorio': typeof PurgatorioRoute
  '/quiz': typeof QuizRoute
  '/search': typeof SearchRoute
  '/inferno/$slug': typeof InfernoSlugRoute
  '/inferno': typeof InfernoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask-dante': typeof AskDanteRoute
  '/cantos': typeof CantosRoute
  '/characters': typeof CharactersRoute
  '/empyrean': typeof EmpyreanRoute
  '/journey': typeof JourneyRoute
  '/paradiso': typeof ParadisoRoute
  '/purgatorio': typeof PurgatorioRoute
  '/quiz': typeof QuizRoute
  '/search': typeof SearchRoute
  '/inferno/$slug': typeof InfernoSlugRoute
  '/inferno/': typeof InfernoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ask-dante'
    | '/cantos'
    | '/characters'
    | '/empyrean'
    | '/journey'
    | '/paradiso'
    | '/purgatorio'
    | '/quiz'
    | '/search'
    | '/inferno/$slug'
    | '/inferno/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask-dante'
    | '/cantos'
    | '/characters'
    | '/empyrean'
    | '/journey'
    | '/paradiso'
    | '/purgatorio'
    | '/quiz'
    | '/search'
    | '/inferno/$slug'
    | '/inferno'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ask-dante'
    | '/cantos'
    | '/characters'
    | '/empyrean'
    | '/journey'
    | '/paradiso'
    | '/purgatorio'
    | '/quiz'
    | '/search'
    | '/inferno/$slug'
    | '/inferno/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AskDanteRoute: typeof AskDanteRoute
  CantosRoute: typeof CantosRoute
  CharactersRoute: typeof CharactersRoute
  EmpyreanRoute: typeof EmpyreanRoute
  JourneyRoute: typeof JourneyRoute
  ParadisoRoute: typeof ParadisoRoute
  PurgatorioRoute: typeof PurgatorioRoute
  QuizRoute: typeof QuizRoute
  SearchRoute: typeof SearchRoute
  InfernoSlugRoute: typeof InfernoSlugRoute
  InfernoIndexRoute: typeof InfernoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-dante': {
      id: '/ask-dante'
      path: '/ask-dante'
      fullPath: '/ask-dante'
      preLoaderRoute: typeof AskDanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cantos': {
      id: '/cantos'
      path: '/cantos'
      fullPath: '/cantos'
      preLoaderRoute: typeof CantosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empyrean': {
      id: '/empyrean'
      path: '/empyrean'
      fullPath: '/empyrean'
      preLoaderRoute: typeof EmpyreanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paradiso': {
      id: '/paradiso'
      path: '/paradiso'
      fullPath: '/paradiso'
      preLoaderRoute: typeof ParadisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purgatorio': {
      id: '/purgatorio'
      path: '/purgatorio'
      fullPath: '/purgatorio'
      preLoaderRoute: typeof PurgatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inferno/': {
      id: '/inferno/'
      path: '/inferno'
      fullPath: '/inferno/'
      preLoaderRoute: typeof InfernoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inferno/$slug': {
      id: '/inferno/$slug'
      path: '/inferno/$slug'
      fullPath: '/inferno/$slug'
      preLoaderRoute: typeof InfernoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AskDanteRoute: AskDanteRoute,
  CantosRoute: CantosRoute,
  CharactersRoute: CharactersRoute,
  EmpyreanRoute: EmpyreanRoute,
  JourneyRoute: JourneyRoute,
  ParadisoRoute: ParadisoRoute,
  PurgatorioRoute: PurgatorioRoute,
  QuizRoute: QuizRoute,
  SearchRoute: SearchRoute,
  InfernoSlugRoute: InfernoSlugRoute,
  InfernoIndexRoute: InfernoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
